examonline/config/routes.rb
Rails.application.routes.draw do
  
  get 'tests/instructions'
  
  get 'tests/finish_test'

  get 'tests/test_paper'

  post 'tests/result'

  get 'admin/home'

  get 'admin/csv_actions'

  get 'users/reset_pass'

  get 'admin/settings'

  get 'admin/stats'
  
  get 'users/adduser'
  
  get 'admin/view'
  
  post 'admin/viewquestions'
  
  get 'admin/viewquestions'
  
  get 'tests/home'
  
  post 'admin/editquestion'
  
  post 'tests/edittest'
  
  delete 'admin/deletequestion'
  
  delete 'admin/deletetest'
  
  post 'admin/view'
  
  post 'tests/settimer'
  
  get 'admin/newques'
  
  get 'admin/newtest'
  
  post 'admin/addtest'
  
  patch 'tests/savetest'
  
  get 'admin/viewtest'
  
  post 'admin/addques'
  
  post 'users/edituser'
  
  post 'users/adminedit'

  delete 'admin/destroyuser'
  
  post 'users/addnew'
  
  post 'users/tryedit'
  
  post 'users/editself'
  
  post 'admin/update'
  
  get 'users/new'

  get 'users/login'
  
  get 'users/logout'

  get 'users/edit'

  get 'users/forgot'

  get 'users/home'
  
  post 'users/create'
  
  post 'tests/test_login'
  
  post 'users/login_attempt'
  
  get 'users/profile'
  
  post 'users/profile'
  
  post 'admin/addcategory'
  
  post 'admin/delcategory'
  
  delete 'admin/destroy_multipletest'
  
  delete 'admin/del_mul_ques'
  
  resources :users do
    collection do
      delete 'destroy_multiple'
    end
  end  
  
  resources :admin do
    collection {
      post :import_questions
    }
  end
  
  resources :admin do
    collection do
      delete 'destroy'
    end
  end 

end

examonline/app/views/admin/csv_actions.csv.erb
<%- headers = ['id', 'question', 'subject', 'multichoice', 'isactive', 'answers', 'options'] -%>
<%= CSV.generate_line headers %>
<%- @questions.each do |question| 
  @optionarr = Array.new 
  question.question_options.each do |option| 
    @optionarr << option.option 
    end 
  @options = @optionarr.join(',')
  @answerarr = Array.new 
  @ans = question.answers.split(",")
  @ans.each do |ans|
    @answerarr << QuestionOption.find(ans).option
    end 
  @answers = @answerarr.join(',') %>
  <%=  raw CSV.generate_line([question.id, question.ques, question.quetype, question.multichoice, question.isactive, @answers, @options]) %>
<%- end -%>

examonline/app/views/admin/csv_actions.html.erb
<% provide(:title, 'CSV File Options') %>
<h1>Download/Upload CSV File</h1>
<h3>Download Questions CSV</h3>
<span class="link"><%= link_to "CSV Download", format: :csv %></span>

<h3>Import Questions CSV</h3>
<%= form_tag url_for(:controller => 'admin', :action => 'import_questions'), multipart: true do %>
  <%= file_field_tag :file %> <span class="btn"><%= submit_tag "Import" %></span>
<% end %>
<p><%= flash[:notice] %></p>

examonline/app/views/admin/editquestion.html.erb
<% provide(:title, 'Edit Question') %>
<script>
  $(document).ready(function() {
    var MaxInputs = 5; //maximum input boxes allowed
    var x = $(".options_div input").length; //initlal options text box count
    if(x == 5)
      $("#addopt").css({"opacity": "0.3"});
    else
      $("#delopt").css({"opacity": "0.3"});
    $("#addopt").click(function(e)  //on add input button click
    {
      if (x < MaxInputs) //max input box allowed
      {
        x++; //text box increment
        $(".options_div").append('<input id="options_o5" type="text" name="options[o5]">');
        $("#delopt").css({"opacity": "1"});
        $("#addopt").css({"opacity": "0.3"});
      }
    });
    $("body").on("click", "#delopt", function(e) { //user click on remove text
      if (x >= 5) {
        $($("#options_o5")).remove(); //remove text box
        x--; //decrement textbox
        $("#addopt").css({"opacity": "1"});
        $("#delopt").css({"opacity": "0.3"});
      }
    });
  });
</script>
  <h1>Add Question</h1>
<div class="forms">
  <div class="forms_container">    
    <br>
    <%=  form_for @question, url: { action: "update" } do |q| %>
      Question:<br> <%= q.text_area 'ques' %><br>
      <div class="select_space">Subject:          <%= collection_select 'quetype', :sub, Subject.all, :subject, :subject, {:selected => @question.quetype} %></div>
      <div class="select_space">Multi Choice: <%= q.select 'multichoice', options_for_select(%w[No Yes], @question.multichoice) %></div>
      <div class="select_space">Is Active:        <%= q.select 'isactive', options_for_select(%w[Active Inactive], @question.isactive) %></div>
      Options:
      <%= image_tag("icons/add_icon.png", :alt => "Add Option", :title => "Add Option", :id =>"addopt") %>
      <%= image_tag("icons/minus_icon.png", :alt => "Delete Option", :title => "Delete Option", :id =>"delopt") %>
      <div class="options_div">
        <% x=0 %>
        <% @question.question_options.each do |option| %>
          <% x=x+1 %>
          <%= text_field_tag "options[o#{x}]", option.option %>
        <% end %>
      </div>
      Answer(s):
      <div class="smallmsg">*For MCQ answers should be comma(',') separated.</div>
      <div class="spcng"><% answ = "" %>
        <% @question.question_options.each do |option| %>
          <% @question.answers.split(",").each do |ans| %>
            <% if option.id == ans.to_i %>
              <% answ = answ + "," + option.option %>
            <% end %>
          <% end %>
        <% end %>
        <% answ[0]="" %>
        <%= text_field_tag 'answers', answ %>
      </div>
      <hr>
      <%= q.submit 'Save Question' %>
    <% end %>
    <%= button_to "Cancel", action: "viewquestions", controller: "admin" %>
  </div>
</div>
<ul class="errors">
  <li><%= flash[:notice]%></li>
  <% if @question.errors.any? %>
    <% for message_error in @question.errors.full_messages %>
      <li><%= message_error %></li>
    <% end %>
  <% end %>
</ul>

examonline/app/views/admin/home.html.erb
<% provide(:title, 'Admin') %>
<h1>Administrator Page</h1>
<p><%= flash[:notice]%></p>
<p>Please click Menu to proceed</p>

examonline/app/views/admin/newques.html.erb
<% provide(:title, 'New Question') %>
<script>
  $(document).ready(function() {
    $("#delopt").css({"opacity": "0.3"});
    var MaxInputs = 5; //maximum input boxes allowed
    var x = $(".options_div input").length; //initlal options text box count 
    $("#addopt").click(function(e)  //on add input button click
    {
      if (x < MaxInputs) //max input box allowed
      {
        x++; //text box increment
        $(".options_div").append('<input id="options_5" type="text" name="options[5]">');
        $("#delopt").css({"opacity": "1"});
        $("#addopt").css({"opacity": "0.3"});
      }
    });
    $("body").on("click", "#delopt", function(e) { //user click on remove text
      if (x == 5) {
        $($("#options_5")).remove(); //remove text box
        x--; //decrement textbox
        $("#addopt").css({"opacity": "1"});
        $("#delopt").css({"opacity": "0.3"});
      }
    });
  });
</script>
  <h1>Add Question</h1>
<div class="forms">
  <div class="forms_container">
    <br>
    <%= form_tag url_for(:controller => 'admin', :action => 'addques'), :method => 'post' do -%>
      Question:<br> <%= text_area_tag 'ques' %><br>
      <div class="select_space">Subject:          <%= collection_select 'quetype', :sub, Subject.all, :subject, :subject %></div>
      <div class="select_space">Multi Choice: <%= select_tag 'multichoice', options_for_select(%w[No Yes]) %></div>
      <div class="select_space">Is Active:        <%= select_tag 'isactive', options_for_select(%w[Active Inactive]) %></div>
      Options:
      <%= image_tag("icons/add_icon.png", :alt => "Add Option", :title => "Add Option", :id =>"addopt") %>
      <%= image_tag("icons/minus_icon.png", :alt => "Delete Option", :title => "Delete Option", :id =>"delopt") %>
      <div class="options_div">  
        <%= text_field_tag 'options[1]' %>
        <%= text_field_tag 'options[2]' %>
        <%= text_field_tag 'options[3]' %>
        <%= text_field_tag 'options[4]' %>
      </div>
      Answer(s):
      <div class="smallmsg">*For MCQ answers should be comma(',') separated.</div>
      <%= text_field_tag 'answers' %>
      <hr>
      <%= submit_tag 'Save Question' %>
    <% end -%>
  </div>
</div>
<ul class="errors">
  <li><%= flash[:notice]%></li>
  <% if @question.errors.any? %>
    <% for message_error in @question.errors.full_messages %>
      <li><%= message_error %></li>
    <% end %>
  <% end %>
</ul>

examonline/app/views/admin/newtest.html.erb
<% provide(:title, 'New Test') %>
  <h1>Add New Test</h1>
<div class="forms">
  <div class="smallmsg">Note: All questions will be picked randomly</div>
  <div class="forms_container">
    <br>
    <%= form_for @test, :url => {:controller => 'admin', :action => 'addtest'} do |t| %>
      <div class="select_space">Subject:          <%= t.collection_select :subject, Subject.all, :subject, :subject %></div>
      Test Duration(minutes):<br><%= t.number_field :duration, :min => "0" %>
      Maximum Question Count:<br><%= t.number_field :quescount, :min => "0" %>
      <div class="select_space">Is Active:        <%= t.select :isactive, options_for_select(%w[Active Inactive]) %></div>
      Test Name:<br><%= t.text_field :testname %>
      Test Login ID:<br><%= t.text_field :testlogin %>
      Password:<br><%= t.password_field :testpass %>
      <hr>
      <%= t.submit :Create %>
    <% end %>
  </div>
</div>
<ul class="errors">
  <li><%= flash[:notice] %></li>
  <% if @test.errors.any? %>
    <% for message_error in @test.errors.full_messages %>
      <li><%= message_error %></li>
    <% end %>
  <% end %>
</ul>

examonline/app/views/admin/settings.html.erb
<% provide(:title, 'Settings') %>
<h1>Settings</h1>
<div class="forms">
  <div class="forms_container">
    <br>
    <%= form_tag url_for(:controller => 'admin', :action => 'addcategory') do %>
      Enter New Subject:
      <%= text_field_tag 'subject' %>
      <%= submit_tag 'Add Subject' %>
    <% end %>
      <%= flash[:notice] %>
      <hr>
    <%= form_tag url_for(:controller => 'admin', :action => 'delcategory') do %>
      Select Subject:
      <%= collection_select 'subject', :sub, Subject.all, :subject, :subject %>
      <%= submit_tag 'Delete Subject', data: { confirm: "Are you sure you want to delete this subject?" } %>
    <% end %>
  </div>
</div>

examonline/app/views/admin/stats.html.erb
<% provide(:title, 'Statistics') %>
<script>
  $(document).ready(function() {
    $('#selectall').click(function(event) {  //on click
      if (this.checked) { // check select status
        $('.questions_check').each(function() { //loop through each checkbox
          this.checked = true;  //select all checkboxes with class "checkbox1"              
        });
      } else {
        $('.questions_check').each(function() { //loop through each checkbox
          this.checked = false; //deselect all checkboxes with class "checkbox1"                      
        });
      }
    });

  });
</script>
<h1>Test Statistics</h1>
<% if @stats %>
  <div class="filter">
    <%= form_tag url_for(:controller => 'admin', :action => 'stats'), method: "get" do %>
      Test ID: <%= text_field_tag 'testid', params[:testid] %>
      Subject: <%= collection_select 'subject', :sub, Subject.all, :subject, :subject, :prompt => true %>
      User: <%= text_field_tag 'user', params[:user] %>
      Questions: <span><%= select_tag 'qnum', options_for_select(['>', '<', '='], params[:qnum]) %><%= number_field_tag 'qnumval', params[:qnumval] %></span>
      Percentage: <span><%= select_tag 'percent', options_for_select(['>', '<', '='], params[:percent]) %><%= number_field_tag 'percentval', params[:percentval] %></span>
      Date: 
      <% if params[:dateval] %>
        <% event = params[:dateval] %>
        <span><%= select_tag 'date', options_for_select([["Before", "<"], ["After", ">"]], params[:date]) %><%= date_select("dateval", "on", order: [:month, :day, :year], default: { day: event["on(3i)"].to_i, month: event["on(2i)"].to_i, year: event["on(1i)"].to_i }) %></span>
      <% else %>
        <span><%= select_tag 'date', options_for_select([["Before", "<"], ["After", ">"]], params[:date]) %><%= date_select("dateval", "on", order: [:month, :day, :year], default: { day: (Time.now.strftime('%d').to_i + 1), month: Time.now.strftime('%m').to_i, year: Time.now.strftime('%Y').to_i }) %></span>
      <% end %>
      <%= submit_tag 'Apply' %>
    <% end %>
    <span class="link"><%= link_to 'Clear', {:action => 'stats'} %></span>
  </div>
<%= form_tag url_for(:action => 'destroy'), method: :delete do %>
  <div class="divtable">
    <div class="table">
      <div class="tr">
        <div class="td"><%= submit_tag "", data: { confirm: "Are you sure you want to delete these?" }%><br>
          <%= check_box_tag "selectall" %>
        </div>
        <div class="td">Test Name</div>
        <div class="td">Test Login ID</div>
        <div class="td">Test Subject</div>    
        <div class="td">User Name</div>
        <div class="td">Correct Answers</div>
        <div class="td">Incorrect Answers</div>
        <div class="td">Total Questions</div>
        <div class="td">Percentage</div>
        <div class="td">Test Date</div>
      </div>
      <% @stats.each do |result| %>
        <div class="tr">
          <% @testname = "" %>
          <% @testlogin = "" %>
          <% @testsub = "" %>
          <% @testques = "" %>
          <%if !(@test = Test.where(id: result.test_id).take).blank? %>
            <% @testname = @test.testname %>
            <% @testlogin = @test.testlogin %>
            <% @testsub = @test.subject %>
            <% @testques = @test.quescount %>
          <% end %>
          <div class="td">
            <%= check_box_tag "results[]", result.id, false, class: "questions_check" %>
            </div>
          <div class="td"><% if @testname.blank? %>
              <em>deleted</em>
            <% else %>
              <%= @testname %>
            <% end %>
          </div>
          <div class="td"><% if @testlogin.blank? %>
              <em>deleted</em>
            <% else %>
              <%= @testlogin %>
            <% end %>
          </div>
          <div class="td"><% if @testsub.blank? %>
              <em>deleted</em>
            <% else %>
              <%= @testsub %>
            <% end %>
          </div>
          <div class="td"><%if !(@user = User.where(id: result.user_id).take).blank? %>
              <%= @user.name %>
            <% else %>
              <em>deleted</em>
            <% end %>
          </div>
          <div class="td"><%= result.correct %></div>
          <div class="td"><%= result.incorrect %></div>
          <div class="td"><% if @testques.blank? %>
              <em>deleted</em>
            <% else %>
              <%= @testques %>
            <% end %>
          </div>
          <div class="td"><%= @percent = (result.correct * 100)/(result.correct + result.incorrect) %>&percnt;</div>
          <div class="td"><%= result.created_at.strftime("%b %d, %Y") %></div>
        </div>
      <% end %>
    </div>
  </div>
  <% end %>
  <div class="apple_pagination">
    <%= will_paginate @stats %>
  </div>
  <div class="average">Average Score: <%= @avg %>&percnt;</div>
  <div class="average">Total Tests: <%= @statcount %></div>
  <div class="average">Number of Users: <%= @usercount %></div>
<% else %>
  <div class="average">No result to display</div>
<% end %>

examonline/app/views/admin/view.html.erb
<% provide(:title, 'Users') %>
<script>
  $(document).ready(function() {
    $('#selectall').click(function(event) {  //on click
      if (this.checked) { // check select status
        $('.users_check').each(function() { //loop through each checkbox
          this.checked = true;  //select all checkboxes with class "checkbox1"              
        });
      } else {
        $('.users_check').each(function() { //loop through each checkbox
          this.checked = false; //deselect all checkboxes with class "checkbox1"                      
        });
      }
    });
  });
</script>
<h1>Users List</h1><%= flash[:notice]%>
<div class="filter">
  <%= form_tag url_for(:controller => 'admin', :action => 'view'), method: "get" do %>
    Name: <%= text_field_tag 'name', params[:name] %>Email:<%= text_field_tag 'email', params[:email] %>
    Experience: <span><%= select_tag 'exp', options_for_select(['>', '<', '='], params[:exp]) %><%= text_field_tag 'expval', params[:expval] %></span>
    Phone: <%= text_field_tag 'phone', params[:phone] %>
    User Type: <%= select_tag 'usertype', options_for_select(['Admin', 'Examinee'], params[:usertype]), {:include_blank => ''} %>
    <%= submit_tag 'Apply' %>
  <% end %>
  <span class="link"><%= link_to 'Clear', {:action => 'view'} %></span>
</div>
<%= form_tag destroy_multiple_users_path, method: :delete do %>
  <div class="divtable" >
    <div class="table">
      <div class="tr">
        <div class="td"><%= submit_tag "", data: { confirm: "Are you sure you want to delete these?" }%><br>
          <%= check_box_tag "selectall" %>
        </div>
        <div class="td">Name</div>
        <div class="td">Email</div>
        <div class="td">Experience</div>
        <div class="td">Phone</div>
        <div class="td">User Type</div>
        <div class="td">Action</div>
      </div>
      <% @users.each do |users| %>
        <div class="tr">
          <div class="td">
            <% if session[:user_id] != users.id %>
              <%= check_box_tag "users[]", users.id, false, class: "users_check" %>
              <% end %>
            </div>
            <div class="td"><%= users.name %></div>
            <div class="td"><%= users.email %></div>
            <div class="td"><%= users.experience %> Years</div>
            <div class="td"><%= users.phone %></div>
            <div class="td"><%= users.usertype %></div>
            <div class="td">
              <% if users.usertype != 'Admin' %>
                <%= link_to(image_tag("icons/edit_icon.svg", :alt => "Edit", :title => "Edit"), {:controller=>'users', :action=>'edituser', :user_id=>users.id}, method: :post) %> 
              <% end %>
              <% if session[:user_id] != users.id %>
                <%= link_to image_tag("icons/bin_icon.png", :alt => "Delete", :title => "Delete"), {:action=>'destroyuser', :id=>users.id}, method: :delete, data: { confirm: "Are you sure you want to delete #{users.usertype} #{users.name}?" } %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="apple_pagination">
    <%= will_paginate @users %>
  </div>

examonline/app/views/admin/viewquestions.html.erb
<% provide(:title, 'Questions') %>
<script>
  $(document).ready(function() {
    $('#selectall').click(function(event) {  //on click
      if (this.checked) { // check select status
        $('.questions_check').each(function() { //loop through each checkbox
          this.checked = true;  //select all checkboxes with class "checkbox1"              
        });
      } else {
        $('.questions_check').each(function() { //loop through each checkbox
          this.checked = false; //deselect all checkboxes with class "checkbox1"                      
        });
      }
    });
  });
</script>
<h1>Questions List</h1><%= flash[:notice]%>
<div class="filter">
  <%= form_tag url_for(:controller => 'admin', :action => 'viewquestions'), method: "get" do %>
    Subject: <%= collection_select 'quetype', :sub, Subject.all, :subject, :subject, {:prompt => true} %>
    Multi Choice: <%= select_tag 'multichoice', options_for_select(%w[No Yes], params[:multichoice]), {:include_blank => 'name of your blank prompt'} %>
    Is Active: <%= select_tag 'isactive', options_for_select(%w[Active Inactive], params[:isactive]), {:include_blank => 'name of your blank prompt'} %>
    <%= submit_tag 'Apply' %>
    <span class="link"><%= link_to 'CSV Opions', {:action => 'csv_actions'} %></span>
  <% end %>
  <span class="link"><%= link_to 'Clear', {:action => 'viewquestions'} %></span>
</div>
<%= form_tag url_for(:controller => 'admin', :action => 'del_mul_ques'), method: :delete do %>
  <div class="divtable">
    <div class="table">
      <div class="tr">
        <div class="td"><%= submit_tag "", data: { confirm: "Are you sure you want to delete these?" } %><br>
          <%= check_box_tag "selectall" %>
        </div>
        <div class="td">Question</div>
        <div class="td">Type</div>
        <div class="td">Is Multi Choice</div>
        <div class="td">Is Active</div>
        <div class="td">Options</div>
        <div class="td">Answers</div>
        <div class="td">Actions</div>
      </div>
      <% @questions.each do |question| %>
        <div class="tr">
          <div class="td">
            <%= check_box_tag "questions[]", question.id, false, class: "questions_check" %>
            </div>
            <div class="td"><%= question.ques %></div>
            <div class="td"><%= question.quetype %></div>
            <div class="td"><%= question.multichoice %></div>
            <div class="td"><%= question.isactive %></div>
            <div class="td"><% question.question_options.each do |option| %>
                <%= option.option %><br>
              <% end %>
            </div>
            <div class="td">
              <% question.question_options.each do |option| %>
                <% question.answers.split(",").each do |ans| %>
                  <% if option.id == ans.to_i %>
                    <%= option.option %><br>
                  <% end %>
                <% end %>
              <% end %>
            </div>
            <div class="td">
              <%= link_to(image_tag("icons/edit_icon.svg", :alt => "Edit", :title => "Edit"), {:action=>'editquestion', :question_id=>question.id}, method: :post) %> 
              <%= link_to(image_tag("icons/bin_icon.png", :alt => "Delete", :title => "Delete"), {:action=>'deletequestion', :id=>question.id}, method: :delete, data: { confirm: "Are you sure you want to delete this question?" }) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="apple_pagination">
    <%= will_paginate @questions %>
  </div>

examonline/app/views/admin/viewtest.html.erb
<% provide(:title, 'Tests') %>
<script>
  $(document).ready(function() {
    $('#selectall').click(function(event) {  //on click
      if (this.checked) { // check select status
        $('.tests_check').each(function() { //loop through each checkbox
          this.checked = true;  //select all checkboxes with class "checkbox1"              
        });
      } else {
        $('.tests_check').each(function() { //loop through each checkbox
          this.checked = false; //deselect all checkboxes with class "checkbox1"                      
        });
      }
    });

  });
</script>
<h1>Tests List</h1><%= flash[:notice]%><%= flash[:success]%>
<div class="filter">
  <%= form_tag url_for(:controller => 'admin', :action => 'viewtest'), method: "get" do %>
    Subject: <%= collection_select 'quetype', :sub, Subject.all, :subject, :subject, :prompt => true %>
    Duration: <span><%= select_tag 'time', options_for_select(['>', '<', '=']) %><%= number_field_tag 'timeval', params[:timeval] %></span>
    Questions: <span><%= select_tag 'qnum', options_for_select(['>', '<', '=']) %><%= number_field_tag 'qnumval', params[:qnumval] %></span>
    Is Active: <%= select_tag 'isactive', options_for_select(%w[Active Inactive], params[:isactive]), {:include_blank => ''} %>
    Created By: <%= text_field_tag 'createdby', params[:createdby] %>
    <%= submit_tag 'Apply' %>
  <% end %>
  <span class="link"><%= link_to 'Clear', {:action => 'viewtest'} %></span>
</div>
<%= form_tag url_for(:controller => 'admin', :action => 'destroy_multipletest'), method: :delete do %>
  <div class="divtable" >
    <div class="table">
      <div class="tr">
        <div class="td"><%= submit_tag "", data: { confirm: "Are you sure you want to delete these?" }%><br>
          <%= check_box_tag "selectall" %>
        </div>
        <div class="td">Subject</div>
        <div class="td">Duration</div>
        <div class="td">Count</div>
        <div class="td">Is Active</div>
        <div class="td">Test Name</div>
        <div class="td">Test Login</div>
        <div class="td">Test Password</div>
        <div class="td">Created By</div>
        <div class="td">Actions</div>
      </div>
      <% @tests.each do |test| %>
        <div class="tr">
          <div class="td">
            <%= check_box_tag "tests[]", test.id, false, class: "tests_check" %>
            </div>
            <div class="td"><%= test.subject %></div>
            <div class="td"><%= test.duration %> Minutes</div>
            <div class="td"><%= test.quescount %> Questions</div>
            <div class="td"><%= test.isactive %></div>
            <div class="td"><%= test.testname %></div>
            <div class="td"><%= test.testlogin %></div>
            <div class="td"><%= test.testpass %></div>
            <div class="td"><% @user=User.where(id: test.createdby).first %>
              <% if @user %>
                <%= @user.name %>
              <% else %>
                <em>deleted</em>
              <% end %>
            </div>
            <div class="td">
              <%= link_to(image_tag("icons/edit_icon.svg", :alt => "Edit", :title => "Edit"), {:controller => 'tests', :action=>'edittest', :test_id=>test.id}, method: :post) %>
              <%= link_to(image_tag("icons/bin_icon.png", :alt => "Delete", :title => "Delete"), {:action=>'deletetest', :id=>test.id}, method: :delete, data: { confirm: "Are you sure you want to delete this test?" }) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="apple_pagination">
    <%= will_paginate @tests %>
  </div>